services:
  - type: web
    name: diet-calculator
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: APP_NAME
        value: DietCalculator
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://diet-calculator.onrender.com
      - key: ELYTICA_APPLICATION_ID
        value: 14
      - key: ELYTICA_TOKEN
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
